klanad_website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from klanad import views


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", views.containers, name="containers"),
        path("group/<uuid:group_id>/", views.group, name="group"),
        path("products/", views.products, name="products"),
        path("product/<uuid:product_id>/", views.product, name="product"),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

klanad/models.py
import uuid

from django.db import models
from django.db.models import CASCADE
from model_utils.models import TimeStampedModel


class Address(models.Model):
    """An Address for a person or entity."""

    street = models.CharField(
        max_length=100, help_text="The name of the street.", null=True, blank=True
    )
    number = models.CharField(
        max_length=25, help_text="The number of the building.", null=True, blank=True
    )
    city = models.CharField(max_length=50, null=True, blank=True)
    country = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        """Meta class."""

        abstract = True


class ContactDetails(models.Model):
    """Contact details for a person or company."""

    email = models.EmailField()
    phone = models.CharField(max_length=30, null=True, blank=True)
    fax = models.CharField(max_length=30, null=True, blank=True)

    class Meta:
        """Meta class."""

        abstract = True


class Contact(ContactDetails):
    """A Contact for a company."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)
    notes = models.TextField(
        help_text="Any notes you want to keep for this contact.", null=True, blank=True
    )

    class Meta:
        """Meta class."""

        app_label = "klanad"

    def __repr__(self) -> str:
        """String representation of a Contact."""
        return f"{self.name}"

    def __str__(self) -> str:
        return self.__repr__()


class Company(TimeStampedModel, Address, ContactDetails):
    """A Company."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=50, help_text="The name of the company.")
    description = models.TextField(null=True, blank=True)
    contact = models.ForeignKey(Contact, on_delete=CASCADE, null=True, blank=True)
    notes = models.TextField(
        help_text="Any notes you want to keep for this company.", null=True, blank=True
    )

    class Meta:
        """Meta class."""

        app_label = "klanad"

    def __repr__(self) -> str:
        """String representation of a Contact."""
        return f"{self.title} - {self.contact.name}"

    def __str__(self) -> str:
        return self.__repr__()


class GroupContainer(models.Model):
    """A Container for groups to seperate them even further."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(help_text="The title of the product.", max_length=256)
    position = models.PositiveIntegerField(
        help_text="The order in which containers are shown, in ascending order.",
        null=True,
        blank=True,
    )

    class Meta:
        """Meta class."""

        ordering = ("position",)
        app_label = "klanad"

    def __repr__(self) -> str:
        """String representation of a Container."""
        return self.title

    def __str__(self) -> str:
        return self.__repr__()


class ProductGroup(models.Model):
    """A group of products."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=50, help_text="The name of the product group.")
    description = models.TextField(null=True, blank=True)
    position = models.PositiveIntegerField(
        help_text="The order in which product groups are shown, in ascending order.",
        null=True,
        blank=True,
    )
    container = models.ForeignKey(
        GroupContainer,
        help_text="Which container does this group belong to.",
        on_delete=CASCADE,
        blank=True,
        null=True,
    )
    archived = models.BooleanField(
        default=False, help_text="ProductGroups which are archived are not shown."
    )

    class Meta:
        """Meta class."""

        ordering = ("container", "position",)
        app_label = "klanad"

    def __repr__(self) -> str:
        """String representation of a Contact."""
        return self.title

    def __str__(self) -> str:
        return self.__repr__()


class Product(TimeStampedModel):
    """A Product."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(help_text="The title of the product.", max_length=256)
    group = models.ForeignKey(ProductGroup, on_delete=CASCADE, blank=True, null=True)
    description = models.TextField(
        help_text="A description for the product.", null=True, blank=True
    )
    position = models.PositiveIntegerField(
        help_text="The order in which products are shown, in ascending order.",
        null=True,
        blank=True,
    )
    archived = models.BooleanField(
        default=False, help_text="Products which are archived are not shown."
    )

    # Private fields
    built_by = models.ForeignKey(
        Company,
        help_text="Which company built this product.",
        on_delete=CASCADE,
        blank=True,
        null=True,
    )

    class Meta:
        """Meta class."""

        ordering = ("group", "position",)
        app_label = "klanad"

    def __repr__(self) -> str:
        """String representation of a Contact."""
        return self.title

    def __str__(self) -> str:
        return self.__repr__()


class ProductGroupImage(TimeStampedModel):
    """Image for a ProductGroup."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    image = models.ImageField(upload_to="product-groups")
    group = models.ForeignKey(ProductGroup, on_delete=CASCADE)

    class Meta:
        """Meta class."""

        app_label = "klanad"

    def __repr__(self) -> str:
        """String representation of a Contact."""
        return f"Image for: {self.group.title}"

    def __str__(self) -> str:
        return self.__repr__()


class ProductImage(TimeStampedModel):
    """An image for a product."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    image = models.ImageField(upload_to="products")
    product = models.ForeignKey(Product, on_delete=CASCADE)
    position = models.PositiveIntegerField(
        help_text="The order in which images are shown, in ascending order.",
        null=True,
        blank=True,
    )

    class Meta:
        """Meta class."""

        ordering = ("position",)
        app_label = "klanad"

    def __repr__(self) -> str:
        """String representation of a Contact."""
        return f"Image for: {self.product.title} with position: {self.position}"

    def __str__(self) -> str:
        return self.__repr__()


class KlanadTranslations(models.Model):
    """Any fields in the website that have dynamic text."""

    welcome_title = models.CharField(
        help_text="Title of the welcome message.", max_length=255
    )
    welcome_message = models.TextField(help_text="Message shown on the landing page.")
    footer_email_me = models.CharField(
        help_text="Message to email the owner of the site.", max_length=100
    )

    def __repr__(self) -> str:
        """String representation of a KlanadTranslation."""
        return "Text fields"

    def __str__(self) -> str:
        return self.__repr__()

    def save(self, *args, **kwargs) -> None:
        """Overloaded to prevent more than 1 of these objects existing."""
        if self.__class__.objects.count() > 0:
            return
        else:
            super().save(args, kwargs)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'klanad.css' %}" />
		<link rel="shortcut icon" href="{% static 'favicon.ico' %}"/>
		<title>Klanad - {% block title %}{% endblock title %}</title>
  	</head>
  	<body>
		<nav class="navbar navbar-light nav-padding">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link klanad-dark-grey" href="{% url 'containers' %}"><span class="oi oi-home"></span></a>
				</li>
			</ul>
			<div class="float-right">
				<img class="img-fluid" height="100rem" width="200rem" src="{% static 'klanad-logo.png' %}"
					 alt="Klanad's
				logo">
			</div>
		</nav>
		<main role="main">
    		{% block content %}{% endblock content %}
		</main>
		<footer class="text-muted">
			<div class="container">
				<p class="float-right"><a href="#"><span class="oi oi-arrow-thick-top"></span></a></p>
				<p>{{ footer_email_me }}:
					<a href="mailto:karel.lansu@klanad.com">karel.lansu@klanad.com</a>
				</p>
			</div>
		</footer>

		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
	</body>
</html>

templates/containers.html
{% extends "base.html" %}

{% block title %}product classes{% endblock title %}

{% block content %}
	<section class="text-center">
		<div class="container pt-3 bg-klanad-light-grey"">
			<h1 class="jumbotron-header">{{ welcome_title }}</h1>
			<p class="lead text-muted pb-3">{{ welcome_message }}</p>
		</div>
	</section>
		{% for container in containers %}
		<div class="container text-center bg-klanad-light-grey mb-3 show">
			<a class="btn btn-primary" data-toggle="collapse" href="#collapse-{{ container.id }}" role="button"
				aria-expanded="true"
				aria-controls="collapse-{{ container.id }}">
				<span class="oi oi-eject"></span>
			</a>
			<div class="container show" id="collapse-{{ container.id }}">
				<div class="pt-2">
					<h3>{{ container.title }}</h3>
				</div>
				<div class="row">
					{% for group in container.productgroup_set.all %}
						<div class="col-sm-4">
							<a href="{% url 'group' group.id %}">
								<div class="card mb-1">
									<div class="card-body">
										<h6>{{ group.title }}</h6>
										<div class="card-body h-100">
											<img src="{{ group.productgroupimage_set.all.0.image.url }}" alt="product image"
												 class="card-img-top img-fluid rounded img-responsive">
										</div>
									</div>
								</div>
							</a>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
		{% endfor %}
{% endblock content %}

templates/group.html
{% extends "base.html" %}

{% block title %}{{ group.title }}{% endblock title %}

{% block content %}
	<section class="jumbotron text-center bg-klanad-light-grey">
		<div class="container">
			<h1 class="jumbotron-header">{{ group.title }}</h1>
			<img class="img-fluid rounded" src="{{ group.productgroupimage_set.all.0.image.url }}" alt="image of a
			group" />
			<p class="lead text-muted">{{ group.description|linebreaks }}</p>
		</div>
	</section>
	<div class="py-5 bg-klanad-light-grey">
		<div class="container">
			<div class="row">
				{% for product in group.product_set.all %}
					<div class="col-md-4">
						<a href="{% url 'product' product.id %}">
						<div class="card mb-5 shadow-sm">
							<div class="card-body h-100 text-center">
								<img src="{{ product.productimage_set.all.0.image.url }}" alt="product image"
									 class="card-img-top img-fluid rounded">
							</div>
							<div class="card-body text-center">
								<h6>{{ product.title }}</h6>
								<p class="card-text">
									{{ product.description }}
								</p>
							</div>
						</div>
						</a>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock content %}

templates/groups.html
{% extends "base.html" %}

{% block title %}product groups{% endblock title %}

{% block content %}
	<section class="jumbotron text-center bg-klanad-light-grey">
		<div class="container">
			<h1 class="jumbotron-header">{{ welcome_title }}</h1>
			<p class="lead text-muted">{{ welcome_message }}</p>
		</div>
	</section>
	<div class="py-5 bg-klanad-light-grey">
		<div class="container">
			<div class="row">
				{% for group in groups %}
					<a href="{% url 'group' group.id %}">
					<div class="col-md-4">
						<div class="card mb-5 shadow-sm">
							<div class="card-body text-center">
								<h6>{{ group.title }}</h6>
								<div class="card-body h-100 text-center">
									<img src="{{ group.productgroupimage_set.all.0.image.url }}" alt="product image"
										 class="card-img-top img-fluid rounded img-responsive">
								</div>
							</div>
						</div>
					</div>
					</a>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock content %}

templates/product.html
{% extends "base.html" %}

{% block title %}{{ product.title }}{% endblock title %}

{% block content %}
	<section class="jumbotron text-center bg-klanad-light-grey">
		<div class="container">
			<h1 class="jumbotron-header">{{ product.title }}</h1>
			<img class="img-fluid rounded" src="{{ product.productimage_set.all.0.image.url }}" alt="image of a product">
			<p class="lead text-muted">{{ product.description|linebreaks }}</p>
		</div>
	</section>
	{% if product.productimage_set.count > 2 %}
	<div class="container">
		<div class="row justify-content-center">
			<div class="row">
				{% for productimage in product.productimage_set.all %}
					<div class="col-md-4">
						<div class="card mb-5 shadow-sm">
							<div class="card-body h-100 text-center">
								<img class="img-fluid rounded" src="{{ productimage.image.url }}" alt="image of a
								product">
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
	{% endif %}
{% endblock content %}

templates/products.html
{% extends "base.html" %}

{% block title %}products{% endblock title %}

{% block content %}
	<div class="py-5 bg-klanad-light-grey">
		<div class="container">
			<div class="row">
				{% for product in products %}
					<a href="{% url 'product' product.id %}">
					<div class="col-md-4">
						<div class="card mb-5 shadow-sm">
							<div class="card-body h-100 text-center">
								<img src="{{ product.productimage_set.all.0.image.url }}" alt="product image"
									 class="card-img-top img-fluid rounded">
							</div>
							<div class="card-body">
								<p class="card-text">
									{{ product.description }}
								</p>
							</div>
						</div>
					</div>
					</a>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock content %}